train_file: ["data/flickr30k_train_small.json"]
val_file: "data/flickr30k_val_small.json"
test_file: "data/flickr30k_test_small.json"

image_root: "../flickr30k_images/flickr30k_images"

train_image_root: '../flickr30k_images/flickr30k_small'
val_image_root: '../flickr30k_images/flickr30k_small_val'
test_image_root: '../flickr30k_images/flickr30k_small_test'


bert_config: "configs/config_bert.json"
resume: "checkpoints/flickr30k.pth"
output_dir: "output_flickr_baseline"


# image_res: 384
# batch_size_train: 32
# batch_size_test: 64

# ---------------------------
# BASIC CONFIGURATION (EDITED)
# ---------------------------
image_res: 224            
batch_size_train: 8       
batch_size_test: 8

output_dir: 'output_flickr_baseline'

# --------------------------

momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128
queue_size: 16


alpha: 0.4
distill: False
warm_up: False

optimizer: {opt: adamW, lr: 0.00001, weight_decay: 0.02} 
schedular: {sched: cosine, lr: 0.00001, epochs: 10, min_lr: 0.00001, decay_rate: 1, warmup_lr: 0.00001, warmup_epochs: 1, cooldown_epochs: 0}




